import React from 'react';
import { Award, Check, MessageSquare } from 'lucide-react';

export default function ResolutionMatrix({ evalResults, onOpenPortalFeedback }) {
  // Extract real ranked solutions from conflictGraph if available
  const rankedFromEval = evalResults?.conflictGraph?.rankedSolutions;

  const tiers = (rankedFromEval && rankedFromEval.length > 0)
    ? rankedFromEval.map(sol => ({
        rank: sol.rank,
        title: sol.name,
        subtitle: sol.workloadDnaMatch || `Rank ${sol.rank} Solution`,
        intentMatch: sol.tradeoffMetrics?.intentAlignment || `${Math.round(sol.score * 100)}%`,
        capex: sol.estimatedCostUsd ? `$${sol.estimatedCostUsd.toLocaleString()}` : '$18,450',
        badgeClass: sol.rank === 1 ? 'badge-emerald' : sol.rank <= 3 ? 'badge-blue' : 'badge-amber',
        rationale: sol.reasoning,
        swaps: sol.tradeoffMetrics ? [
          `Modifications: ${sol.tradeoffMetrics.skuModifications}`,
          `Cost Delta: ${sol.tradeoffMetrics.costDeltaUsd}`,
          `Expansion: ${sol.tradeoffMetrics.capacityExpansion}`
        ] : ['Standard physical fix injected']
      }))
    : [
        {
          rank: 1,
          title: 'Rank 1: Workload Intent Alignment',
          subtitle: 'Customer Workload Match',
          intentMatch: '98%',
          capex: '$18,450',
          badgeClass: 'badge-emerald',
          rationale: 'Includes SAP HANA optimized memory density & high-TDP processor cooling.',
          swaps: ['P49057-B21 -> Intel Xeon Gold 6430', 'P38620-B21 -> 16x 32GB DDR5-5600']
        },
        {
          rank: 2,
          title: 'Rank 2: Standardized CTO Baseline',
          subtitle: 'Factory Standard CTO',
          intentMatch: '92%',
          capex: '$16,800',
          badgeClass: 'badge-blue',
          rationale: 'Standard factory baseline CTO build without custom thermal overhead.',
          swaps: ['P49057-B21 -> Standard Fan Kit']
        },
        {
          rank: 3,
          title: 'Rank 3: High-IOPS Storage Optimized',
          subtitle: 'Storage Density Tier',
          intentMatch: '88%',
          capex: '$21,200',
          badgeClass: 'badge-blue',
          rationale: 'Tri-Mode cabling with 8x NVMe Read-Intensive SFF drives.',
          swaps: ['P76453-B21 Tri-Mode Cable added', 'P26934-B21 1.92TB NVMe RI']
        },
        {
          rank: 4,
          title: 'Rank 4: Maximum Density Expansion',
          subtitle: 'Headroom Tier',
          intentMatch: '84%',
          capex: '$24,100',
          badgeClass: 'badge-amber',
          rationale: 'Dual processor with secondary PCIe riser installed for future GPU expandability.',
          swaps: ['P49057-B21 Dual Socket', 'P38620-B21 Secondary Riser']
        },
        {
          rank: 5,
          title: 'Rank 5: CapEx Minimized Buildable',
          subtitle: 'Budget Optimized Tier',
          intentMatch: '76%',
          capex: '$14,900',
          badgeClass: 'badge-amber',
          rationale: 'Minimum viable build passing 100% of physical constraints at lowest CapEx.',
          swaps: ['P49057-B21 Single Socket', 'P38620-B21 8x 32GB DDR5']
        }
      ];

  return (
    <div className="space-y-6">
      <div className="glass-card p-6">
        <div className="border-b border-slate-100 pb-3 mb-4">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Award className="w-5 h-5 text-emerald-600" />
            5-Tier Strategic Resolution Matrix Cards
          </h2>
          <p className="text-xs text-slate-500">
            Multi-tiered valid build candidates generated by the Vendor BOM Comparison Engine.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {tiers.map(tier => (
            <div
              key={tier.rank}
              className={`rounded-2xl p-5 border transition-all glass-card ${
                tier.rank === 1 ? 'border-emerald-300 ring-2 ring-emerald-500/20 bg-emerald-50/10' : 'border-slate-200'
              }`}
            >
              <div className="flex items-center justify-between mb-3">
                <span className={`badge ${tier.badgeClass}`}>{tier.subtitle}</span>
                <span className="text-xs font-bold text-slate-500">Match: {tier.intentMatch}</span>
              </div>

              <h3 className="font-bold text-slate-900 text-sm mb-1">{tier.title}</h3>
              <p className="text-xs text-slate-500 mb-3">{tier.rationale}</p>

              <div className="bg-slate-50 p-3 rounded-xl border border-slate-100 mb-4">
                <div className="flex justify-between items-center text-xs">
                  <span className="text-slate-500 font-medium">Estimated CapEx:</span>
                  <span className="font-bold text-slate-900 text-sm">{tier.capex}</span>
                </div>
              </div>

              <div className="space-y-1 mb-4">
                <p className="text-[11px] font-semibold text-slate-600 uppercase">Key SKU Swaps:</p>
                {tier.swaps.map((swap, idx) => (
                  <p key={idx} className="mono text-[10px] text-slate-600 flex items-center gap-1">
                    <Check className="w-3 h-3 text-emerald-600 shrink-0" />
                    {swap}
                  </p>
                ))}
              </div>

              <button
                onClick={() => onOpenPortalFeedback(tier)}
                className="w-full btn-secondary justify-center text-xs"
              >
                <MessageSquare className="w-3.5 h-3.5 text-blue-600" />
                Log Portal Feedback
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
